# Generated by Django 5.2.2 on 2025-06-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
